import express from 'express';
// import { getCourse, getCourses, createCourse, updateCourse, deleteCourse } from '../controllers/courses.js';
// import auth from '../middleware/auth.js';
// import admin from '../middleware/admin.js';
const router = express.Router();
// router.get('/', getCourses);
// router.get('/:id', getCourse);
// router.post('/', auth, createCourse);
// router.put('/:id', auth, updateCourse);
// router.delete('/:id', [auth, admin], deleteCourse);
export default router;
